### PR TITLE
Support for Crafty 0.7.0

### PR DESCRIPTION
**Pull request by matthijsgroen**
- Uses the Crafty 0.7.0 Motion component as base (just as the crafty Multiway does). This handles the motion and the events like direction changes and movement.
- Speed is now in px/sec (like all Crafty components now are) instead of px/frame
- Updated version numbers as well, and is ready for publication

### CODE REVIEW

**Comment by matthijsgroen** [comment]
Somehow when changing directions a lot the movement gets stalled. Releasing the joystick and pressing again resolves this. I will try to pinpoint the issue and add another commit for this.

**Comment by matthijsgroen** [comment]
Done!

**Comment by svenjacobs** [comment]
Thanks!

**Comment by matthijsgroen** [comment]
That was fast! Thanks!

**Pull request merged**
